version: '3.8'
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default_database
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  discord-bot:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database

